### PR TITLE
Added Bayesian A/B Test analysis

### PR DESCRIPTION
**Pull request by akashrajkn**
Fixes jasp-stats/INTERNAL-jasp#693. 

(I haven't added the NL version of help)

### CODE REVIEW

**Comment by boutinb** [comment]
@akashrajkn Who do you think is the best to review this request?

**Comment by akashrajkn** [comment]
@boutinb I think Quentin is the best person to review this. But I don't know if he has the time for it.

@TimKDJ can you review this PR?

**Comment by TimKDJ** [comment]
For 0.13 this will need to be added to the [JASP package in jasp-desktop](https://github.com/jasp-stats/jasp-desktop/tree/stable/JASP-Engine/JASP/R) still. But you can use the method described above

**Comment by akashrajkn** [comment]
This was added to jasp-desktop repo (jasp-stats/jasp-desktop#4131)

**Pull request closed without merging**
